### ISSUE TITLE
nodejs-docs-samples/functions/scheduleinstance/ won't start all VMs

### ISSUE THREAD

**Issue by gitHu6-newb** [googleapis/nodejs-compute#485]
1) Is this a client library issue or a product issue?
Sry, i have no idea what that means

#### Environment details

  - OS: Debian 10
  - Node.js version: 10
  - npm version: didn't use. I stay in a browser
  - `@google-cloud/compute` version: ^2.0.0

#### Steps to reproduce

  1. Create at least 2 VMs across different regions or zones
  2. Use the examples from https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/functions/scheduleinstance
  3. Make and run the jobs to ping a restart of the VMs
  4. Check the log for each individual VM. Most, if not all, will not show anything that indicates a restart was triggered. For some reason, only my VMs that were created before early July will restart.

#### Things to note:

  A. after [vms].map = async... by checking vms.length, looks like it's 0 for anytime the label is unique for a VM that has a zone different from where the job scheduler lives
  B. Replacing line 38 with const options = {filter: ``};  leads to desired results.
  C. line 101 seems to output the success message even if the contents of the if statement don't execute.

**Comment by laljikanjareeya** [comment]
@gitHu6-newb In order to [start](https://cloud.google.com/compute/docs/reference/rest/v1/instances/start) and [stop](https://cloud.google.com/compute/docs/reference/rest/v1/instances/stop) the instance `zone` is required even if you remove the label filter from option  you need to pass the zone every time.
If you have multiple instances in same zone with same label than `startInstancePubSub` function works as expected.

here is the working example where two instances in same zone and have same label:
```ts
    const compute = new Compute();
    const zone = compute.zone('us-central1-c');
    await zone.createVM('test-vm', { 
        os: 'ubuntu',
        labels:{
            env: 'prod'
        }
     });

    await zone.createVM('test-vm-1', {
        os: 'debian',
        labels: {
            env: 'prod'
        }
    });
```

you can call `startInstancePubSub` as below to start both the instances:

```ts
const pubsubData =  { zone: 'us-central1-c', label: 'env=prod' } ;
const eventData ={data: Buffer.from(JSON.stringify(pubsubData).toString('base64'))};
startInstancePubSub(eventData, null, (errr, message) => {
    console.log('message: ', message);
});
```

I will create PR shortly for label filter to be option for both the functions.

**Comment by fhinkel** [comment]
Moved over to https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2157
