### ISSUE TITLE
`aggregatedList()` API function missing

### ISSUE THREAD

**Issue by mscdex** [googleapis/nodejs-compute#675]
#### Environment details

  - OS: n/a
  - Node.js version: v16.13.2
  - npm version: n/a
  - `@google-cloud/compute` version: 3.1.0

The `aggregatedList()` API function appears to be missing. From what I understand with the other `*list()` functions, it's supposed to buffer all of the results into a single collection/array. The documentation for `aggregatedListAsync()` even refers to this function:

> Equivalent to `aggregatedList`, but returns an iterable object.

**Comment by alexander-fenster** [comment]
> Equivalent to `aggregatedList`, but returns an iterable object.

I wasn't able to find a line like this anywhere in the sources - looks like it was a documentation bug and was likely fixed :)

We don't suggest using non-async `list` functions because they are uncontrollable, they keep querying for results, cannot be stopped, and can easily hit quotas. Compute has a special type of paginated methods that basically returns a map with string key and paginated values; we do not provide non-async methods for querying such RPCs.
