### ISSUE TITLE
Support gcloud beta compute instance create-with-container?

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-compute#68]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2817

<a href="/lopezm94"><img src="https://avatars2.githubusercontent.com/u/14032787?s=88&v=4" height=44 width=44 align=left></a>@lopezm94<br>April 27, 2018 1:21 PM

Is there support for compute beta features in the library? I would like to deploy a docker image with a specific guest environment variable file, in the way `gcloud beta compute instance create-with-container --container-env-file <env-file>` lets you do it.

Thanks

**Comment by lopezm94** [comment]
Sure, though I can't promise anything. I'm quite unfamiliar to the code base, would you mind pointing me which parts of this repo need to be modified? Also, I would need some way to ask the devs how that gcloud SDK function works (can only find this [mirror](https://github.com/google-cloud-sdk/google-cloud-sdk)).

Would be really nice to have this feature.

**Comment by ManuelGodinoCueto** [comment]
Hi, is there any advance with this issue?

I have been trying to launch an instance from a container and the only solution by now is executing gcloud from Node.

I have tried to create a VM from an instance using vm.create(config) without success and I think the reason is related with the comment that appears on the metadata key when you press "Equivalent REST" when you fill out a VM template deploying a container image using the Cloud Console: "This container declaration format is not public API and may change without notice. Please use gcloud command-line tool or Google Cloud Console to run Containers on Google Compute Engine.".

This information tells me that maybe is not possible to have this feature available at the moment as long as the container declaration format is not public API.
