### ISSUE TITLE
operation.promise() should be explained in the Client API Reference

### ISSUE THREAD

**Issue by fhinkel** [googleapis/nodejs-compute#81]
I don't see `operation.promise()` explained in the [Client API Reference](https://cloud.google.com/nodejs/docs/reference/compute/0.10.x/). It's used in a few examples but not mentioned in [Operation](https://cloud.google.com/nodejs/docs/reference/compute/0.10.x/Operation). 

Did I miss it? If not, can we add a section for that?

The example for `operation` list three listeners. Is that the complete list? Could we get a separate section for the listeners in `Contents`?

**Comment by sduskis** [comment]
@stephenplusplus, is there any update?

**Comment by callmehiphop** [comment]
Unfortunately I don't think there's a way to include a reference to the [common operation class](https://github.com/googleapis/nodejs-common/blob/master/src/operation.ts#L27) where this method lives. Probably worth nothing that this actually affects [other APIs](https://cloud.google.com/nodejs/docs/reference/bigquery/2.0.x/Job). 

It would be great if we could get the common operation listed as an abstract type, otherwise we'll either need to link to the [`gax.Operation`](https://googleapis.github.io/gax-nodejs/Operation) or else copypasta the common docs as a virtual member.

**Comment by JustinBeckwith** [comment]
Closing this, as we're tracking it broadly here: https://github.com/googleapis/google-cloud-node/issues/2894
